//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Assignment2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class baxtech_clinicEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new baxtech_clinicEntities object using the connection string found in the 'baxtech_clinicEntities' section of the application configuration file.
        /// </summary>
        public baxtech_clinicEntities() : base("name=baxtech_clinicEntities", "baxtech_clinicEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new baxtech_clinicEntities object.
        /// </summary>
        public baxtech_clinicEntities(string connectionString) : base(connectionString, "baxtech_clinicEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new baxtech_clinicEntities object.
        /// </summary>
        public baxtech_clinicEntities(EntityConnection connection) : base(connection, "baxtech_clinicEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetInPatients_Result> GetInPatients()
        {
            return base.ExecuteFunction<GetInPatients_Result>("GetInPatients");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetOutPatients_Result> GetOutPatients()
        {
            return base.ExecuteFunction<GetOutPatients_Result>("GetOutPatients");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="visitId">No Metadata Documentation available.</param>
        public ObjectResult<Nullable<global::System.Int32>> FindVisit(Nullable<global::System.Int32> visitId)
        {
            ObjectParameter visitIdParameter;
            if (visitId.HasValue)
            {
                visitIdParameter = new ObjectParameter("VisitId", visitId);
            }
            else
            {
                visitIdParameter = new ObjectParameter("VisitId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<Nullable<global::System.Int32>>("FindVisit", visitIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="visitId">No Metadata Documentation available.</param>
        public ObjectResult<VisitDetailsForVisit_Result> VisitDetailsForVisit(Nullable<global::System.Int32> visitId)
        {
            ObjectParameter visitIdParameter;
            if (visitId.HasValue)
            {
                visitIdParameter = new ObjectParameter("VisitId", visitId);
            }
            else
            {
                visitIdParameter = new ObjectParameter("VisitId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<VisitDetailsForVisit_Result>("VisitDetailsForVisit", visitIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="visitId">No Metadata Documentation available.</param>
        /// <param name="symptoms">No Metadata Documentation available.</param>
        /// <param name="disease">No Metadata Documentation available.</param>
        /// <param name="treatment">No Metadata Documentation available.</param>
        public int RecordVisitDetails(Nullable<global::System.Int32> visitId, global::System.String symptoms, global::System.String disease, global::System.String treatment)
        {
            ObjectParameter visitIdParameter;
            if (visitId.HasValue)
            {
                visitIdParameter = new ObjectParameter("VisitId", visitId);
            }
            else
            {
                visitIdParameter = new ObjectParameter("VisitId", typeof(global::System.Int32));
            }
    
            ObjectParameter symptomsParameter;
            if (symptoms != null)
            {
                symptomsParameter = new ObjectParameter("Symptoms", symptoms);
            }
            else
            {
                symptomsParameter = new ObjectParameter("Symptoms", typeof(global::System.String));
            }
    
            ObjectParameter diseaseParameter;
            if (disease != null)
            {
                diseaseParameter = new ObjectParameter("Disease", disease);
            }
            else
            {
                diseaseParameter = new ObjectParameter("Disease", typeof(global::System.String));
            }
    
            ObjectParameter treatmentParameter;
            if (treatment != null)
            {
                treatmentParameter = new ObjectParameter("Treatment", treatment);
            }
            else
            {
                treatmentParameter = new ObjectParameter("Treatment", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("RecordVisitDetails", visitIdParameter, symptomsParameter, diseaseParameter, treatmentParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetPatients_Result> GetPatients()
        {
            return base.ExecuteFunction<GetPatients_Result>("GetPatients");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="address">No Metadata Documentation available.</param>
        /// <param name="dateOfBirth">No Metadata Documentation available.</param>
        /// <param name="phone">No Metadata Documentation available.</param>
        /// <param name="emergencyContact">No Metadata Documentation available.</param>
        public int AddPatient(global::System.String name, global::System.String address, Nullable<global::System.DateTime> dateOfBirth, global::System.String phone, global::System.String emergencyContact)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("Name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("Name", typeof(global::System.String));
            }
    
            ObjectParameter addressParameter;
            if (address != null)
            {
                addressParameter = new ObjectParameter("Address", address);
            }
            else
            {
                addressParameter = new ObjectParameter("Address", typeof(global::System.String));
            }
    
            ObjectParameter dateOfBirthParameter;
            if (dateOfBirth.HasValue)
            {
                dateOfBirthParameter = new ObjectParameter("DateOfBirth", dateOfBirth);
            }
            else
            {
                dateOfBirthParameter = new ObjectParameter("DateOfBirth", typeof(global::System.DateTime));
            }
    
            ObjectParameter phoneParameter;
            if (phone != null)
            {
                phoneParameter = new ObjectParameter("Phone", phone);
            }
            else
            {
                phoneParameter = new ObjectParameter("Phone", typeof(global::System.String));
            }
    
            ObjectParameter emergencyContactParameter;
            if (emergencyContact != null)
            {
                emergencyContactParameter = new ObjectParameter("EmergencyContact", emergencyContact);
            }
            else
            {
                emergencyContactParameter = new ObjectParameter("EmergencyContact", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("AddPatient", nameParameter, addressParameter, dateOfBirthParameter, phoneParameter, emergencyContactParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="doctorID">No Metadata Documentation available.</param>
        public ObjectResult<GetInPatients_Result> ActiveTreatmentsByDoctor(Nullable<global::System.Int32> doctorID)
        {
            ObjectParameter doctorIDParameter;
            if (doctorID.HasValue)
            {
                doctorIDParameter = new ObjectParameter("DoctorID", doctorID);
            }
            else
            {
                doctorIDParameter = new ObjectParameter("DoctorID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<GetInPatients_Result>("ActiveTreatmentsByDoctor", doctorIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="doctorID">No Metadata Documentation available.</param>
        public ObjectResult<GetOutPatients_Result> PastVisitsToDoctor(Nullable<global::System.Int32> doctorID)
        {
            ObjectParameter doctorIDParameter;
            if (doctorID.HasValue)
            {
                doctorIDParameter = new ObjectParameter("DoctorID", doctorID);
            }
            else
            {
                doctorIDParameter = new ObjectParameter("DoctorID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<GetOutPatients_Result>("PastVisitsToDoctor", doctorIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="patientId">No Metadata Documentation available.</param>
        /// <param name="doctorId">No Metadata Documentation available.</param>
        public int NewOutPatient(Nullable<global::System.Int32> patientId, Nullable<global::System.Int32> doctorId)
        {
            ObjectParameter patientIdParameter;
            if (patientId.HasValue)
            {
                patientIdParameter = new ObjectParameter("PatientId", patientId);
            }
            else
            {
                patientIdParameter = new ObjectParameter("PatientId", typeof(global::System.Int32));
            }
    
            ObjectParameter doctorIdParameter;
            if (doctorId.HasValue)
            {
                doctorIdParameter = new ObjectParameter("DoctorId", doctorId);
            }
            else
            {
                doctorIdParameter = new ObjectParameter("DoctorId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("NewOutPatient", patientIdParameter, doctorIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="patientId">No Metadata Documentation available.</param>
        /// <param name="doctorId">No Metadata Documentation available.</param>
        /// <param name="bedId">No Metadata Documentation available.</param>
        public int NewInPatient(Nullable<global::System.Int32> patientId, Nullable<global::System.Int32> doctorId, Nullable<global::System.Int32> bedId)
        {
            ObjectParameter patientIdParameter;
            if (patientId.HasValue)
            {
                patientIdParameter = new ObjectParameter("PatientId", patientId);
            }
            else
            {
                patientIdParameter = new ObjectParameter("PatientId", typeof(global::System.Int32));
            }
    
            ObjectParameter doctorIdParameter;
            if (doctorId.HasValue)
            {
                doctorIdParameter = new ObjectParameter("DoctorId", doctorId);
            }
            else
            {
                doctorIdParameter = new ObjectParameter("DoctorId", typeof(global::System.Int32));
            }
    
            ObjectParameter bedIdParameter;
            if (bedId.HasValue)
            {
                bedIdParameter = new ObjectParameter("BedId", bedId);
            }
            else
            {
                bedIdParameter = new ObjectParameter("BedId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("NewInPatient", patientIdParameter, doctorIdParameter, bedIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="visitID">No Metadata Documentation available.</param>
        public int DischargeVisit(Nullable<global::System.Int32> visitID)
        {
            ObjectParameter visitIDParameter;
            if (visitID.HasValue)
            {
                visitIDParameter = new ObjectParameter("VisitID", visitID);
            }
            else
            {
                visitIDParameter = new ObjectParameter("VisitID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("DischargeVisit", visitIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetDoctors_Result> GetDoctors()
        {
            return base.ExecuteFunction<GetDoctors_Result>("GetDoctors");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<Beds_Result> FreeBeds()
        {
            return base.ExecuteFunction<Beds_Result>("FreeBeds");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<OccupiedBeds_Result> OccupiedBeds()
        {
            return base.ExecuteFunction<OccupiedBeds_Result>("OccupiedBeds");
        }

        #endregion
    }
    

    #endregion
    
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="baxtech_clinicModel", Name="Beds_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class Beds_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Beds_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="bedName">Initial value of the BedName property.</param>
        /// <param name="ratePerDay">Initial value of the RatePerDay property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static Beds_Result CreateBeds_Result(global::System.Int32 id, global::System.String bedName, global::System.Decimal ratePerDay, global::System.String description)
        {
            Beds_Result beds_Result = new Beds_Result();
            beds_Result.Id = id;
            beds_Result.BedName = bedName;
            beds_Result.RatePerDay = ratePerDay;
            beds_Result.Description = description;
            return beds_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BedName
        {
            get
            {
                return _BedName;
            }
            set
            {
                OnBedNameChanging(value);
                ReportPropertyChanging("BedName");
                _BedName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BedName");
                OnBedNameChanged();
            }
        }
        private global::System.String _BedName;
        partial void OnBedNameChanging(global::System.String value);
        partial void OnBedNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal RatePerDay
        {
            get
            {
                return _RatePerDay;
            }
            set
            {
                OnRatePerDayChanging(value);
                ReportPropertyChanging("RatePerDay");
                _RatePerDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RatePerDay");
                OnRatePerDayChanged();
            }
        }
        private global::System.Decimal _RatePerDay;
        partial void OnRatePerDayChanging(global::System.Decimal value);
        partial void OnRatePerDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="baxtech_clinicModel", Name="GetDoctors_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetDoctors_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetDoctors_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        public static GetDoctors_Result CreateGetDoctors_Result(global::System.Int32 id, global::System.String name, global::System.String address, global::System.String phone)
        {
            GetDoctors_Result getDoctors_Result = new GetDoctors_Result();
            getDoctors_Result.Id = id;
            getDoctors_Result.Name = name;
            getDoctors_Result.Address = address;
            getDoctors_Result.Phone = phone;
            return getDoctors_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PatientsInCare
        {
            get
            {
                return _PatientsInCare;
            }
            set
            {
                OnPatientsInCareChanging(value);
                ReportPropertyChanging("PatientsInCare");
                _PatientsInCare = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PatientsInCare");
                OnPatientsInCareChanged();
            }
        }
        private Nullable<global::System.Int32> _PatientsInCare;
        partial void OnPatientsInCareChanging(Nullable<global::System.Int32> value);
        partial void OnPatientsInCareChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="baxtech_clinicModel", Name="GetInPatients_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetInPatients_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetInPatients_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="doctorId">Initial value of the DoctorId property.</param>
        /// <param name="patientId">Initial value of the PatientId property.</param>
        /// <param name="patientName">Initial value of the PatientName property.</param>
        /// <param name="doctorName">Initial value of the DoctorName property.</param>
        /// <param name="dateOfVisit">Initial value of the DateOfVisit property.</param>
        /// <param name="bedName">Initial value of the BedName property.</param>
        public static GetInPatients_Result CreateGetInPatients_Result(global::System.Int32 id, global::System.Int32 doctorId, global::System.Int32 patientId, global::System.String patientName, global::System.String doctorName, global::System.DateTime dateOfVisit, global::System.String bedName)
        {
            GetInPatients_Result getInPatients_Result = new GetInPatients_Result();
            getInPatients_Result.Id = id;
            getInPatients_Result.DoctorId = doctorId;
            getInPatients_Result.PatientId = patientId;
            getInPatients_Result.PatientName = patientName;
            getInPatients_Result.DoctorName = doctorName;
            getInPatients_Result.DateOfVisit = dateOfVisit;
            getInPatients_Result.BedName = bedName;
            return getInPatients_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DoctorId
        {
            get
            {
                return _DoctorId;
            }
            set
            {
                OnDoctorIdChanging(value);
                ReportPropertyChanging("DoctorId");
                _DoctorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DoctorId");
                OnDoctorIdChanged();
            }
        }
        private global::System.Int32 _DoctorId;
        partial void OnDoctorIdChanging(global::System.Int32 value);
        partial void OnDoctorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PatientId
        {
            get
            {
                return _PatientId;
            }
            set
            {
                OnPatientIdChanging(value);
                ReportPropertyChanging("PatientId");
                _PatientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PatientId");
                OnPatientIdChanged();
            }
        }
        private global::System.Int32 _PatientId;
        partial void OnPatientIdChanging(global::System.Int32 value);
        partial void OnPatientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BedId
        {
            get
            {
                return _BedId;
            }
            set
            {
                OnBedIdChanging(value);
                ReportPropertyChanging("BedId");
                _BedId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BedId");
                OnBedIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BedId;
        partial void OnBedIdChanging(Nullable<global::System.Int32> value);
        partial void OnBedIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DetailsId
        {
            get
            {
                return _DetailsId;
            }
            set
            {
                OnDetailsIdChanging(value);
                ReportPropertyChanging("DetailsId");
                _DetailsId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DetailsId");
                OnDetailsIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DetailsId;
        partial void OnDetailsIdChanging(Nullable<global::System.Int32> value);
        partial void OnDetailsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PatientName
        {
            get
            {
                return _PatientName;
            }
            set
            {
                OnPatientNameChanging(value);
                ReportPropertyChanging("PatientName");
                _PatientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PatientName");
                OnPatientNameChanged();
            }
        }
        private global::System.String _PatientName;
        partial void OnPatientNameChanging(global::System.String value);
        partial void OnPatientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DoctorName
        {
            get
            {
                return _DoctorName;
            }
            set
            {
                OnDoctorNameChanging(value);
                ReportPropertyChanging("DoctorName");
                _DoctorName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DoctorName");
                OnDoctorNameChanged();
            }
        }
        private global::System.String _DoctorName;
        partial void OnDoctorNameChanging(global::System.String value);
        partial void OnDoctorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfVisit
        {
            get
            {
                return _DateOfVisit;
            }
            set
            {
                OnDateOfVisitChanging(value);
                ReportPropertyChanging("DateOfVisit");
                _DateOfVisit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfVisit");
                OnDateOfVisitChanged();
            }
        }
        private global::System.DateTime _DateOfVisit;
        partial void OnDateOfVisitChanging(global::System.DateTime value);
        partial void OnDateOfVisitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BedName
        {
            get
            {
                return _BedName;
            }
            set
            {
                OnBedNameChanging(value);
                ReportPropertyChanging("BedName");
                _BedName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BedName");
                OnBedNameChanged();
            }
        }
        private global::System.String _BedName;
        partial void OnBedNameChanging(global::System.String value);
        partial void OnBedNameChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="baxtech_clinicModel", Name="GetOutPatients_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetOutPatients_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetOutPatients_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="doctorId">Initial value of the DoctorId property.</param>
        /// <param name="dateOfVisit">Initial value of the DateOfVisit property.</param>
        /// <param name="patientName">Initial value of the PatientName property.</param>
        /// <param name="doctorName">Initial value of the DoctorName property.</param>
        public static GetOutPatients_Result CreateGetOutPatients_Result(global::System.Int32 id, global::System.Int32 doctorId, global::System.DateTime dateOfVisit, global::System.String patientName, global::System.String doctorName)
        {
            GetOutPatients_Result getOutPatients_Result = new GetOutPatients_Result();
            getOutPatients_Result.Id = id;
            getOutPatients_Result.DoctorId = doctorId;
            getOutPatients_Result.DateOfVisit = dateOfVisit;
            getOutPatients_Result.PatientName = patientName;
            getOutPatients_Result.DoctorName = doctorName;
            return getOutPatients_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DoctorId
        {
            get
            {
                return _DoctorId;
            }
            set
            {
                OnDoctorIdChanging(value);
                ReportPropertyChanging("DoctorId");
                _DoctorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DoctorId");
                OnDoctorIdChanged();
            }
        }
        private global::System.Int32 _DoctorId;
        partial void OnDoctorIdChanging(global::System.Int32 value);
        partial void OnDoctorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfVisit
        {
            get
            {
                return _DateOfVisit;
            }
            set
            {
                OnDateOfVisitChanging(value);
                ReportPropertyChanging("DateOfVisit");
                _DateOfVisit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfVisit");
                OnDateOfVisitChanged();
            }
        }
        private global::System.DateTime _DateOfVisit;
        partial void OnDateOfVisitChanging(global::System.DateTime value);
        partial void OnDateOfVisitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateOfDischarge
        {
            get
            {
                return _DateOfDischarge;
            }
            set
            {
                OnDateOfDischargeChanging(value);
                ReportPropertyChanging("DateOfDischarge");
                _DateOfDischarge = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfDischarge");
                OnDateOfDischargeChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateOfDischarge;
        partial void OnDateOfDischargeChanging(Nullable<global::System.DateTime> value);
        partial void OnDateOfDischargeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PatientName
        {
            get
            {
                return _PatientName;
            }
            set
            {
                OnPatientNameChanging(value);
                ReportPropertyChanging("PatientName");
                _PatientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PatientName");
                OnPatientNameChanged();
            }
        }
        private global::System.String _PatientName;
        partial void OnPatientNameChanging(global::System.String value);
        partial void OnPatientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DoctorName
        {
            get
            {
                return _DoctorName;
            }
            set
            {
                OnDoctorNameChanging(value);
                ReportPropertyChanging("DoctorName");
                _DoctorName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DoctorName");
                OnDoctorNameChanged();
            }
        }
        private global::System.String _DoctorName;
        partial void OnDoctorNameChanging(global::System.String value);
        partial void OnDoctorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BedName
        {
            get
            {
                return _BedName;
            }
            set
            {
                OnBedNameChanging(value);
                ReportPropertyChanging("BedName");
                _BedName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BedName");
                OnBedNameChanged();
            }
        }
        private global::System.String _BedName;
        partial void OnBedNameChanging(global::System.String value);
        partial void OnBedNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DetailsId
        {
            get
            {
                return _DetailsId;
            }
            set
            {
                OnDetailsIdChanging(value);
                ReportPropertyChanging("DetailsId");
                _DetailsId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DetailsId");
                OnDetailsIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DetailsId;
        partial void OnDetailsIdChanging(Nullable<global::System.Int32> value);
        partial void OnDetailsIdChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="baxtech_clinicModel", Name="GetPatients_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetPatients_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GetPatients_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="emergencyContact">Initial value of the EmergencyContact property.</param>
        /// <param name="dateOfRegistration">Initial value of the DateOfRegistration property.</param>
        public static GetPatients_Result CreateGetPatients_Result(global::System.Int32 id, global::System.String name, global::System.String address, global::System.DateTime dateOfBirth, global::System.String phone, global::System.String emergencyContact, global::System.DateTime dateOfRegistration)
        {
            GetPatients_Result getPatients_Result = new GetPatients_Result();
            getPatients_Result.Id = id;
            getPatients_Result.Name = name;
            getPatients_Result.Address = address;
            getPatients_Result.DateOfBirth = dateOfBirth;
            getPatients_Result.Phone = phone;
            getPatients_Result.EmergencyContact = emergencyContact;
            getPatients_Result.DateOfRegistration = dateOfRegistration;
            return getPatients_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.DateTime _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTime value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmergencyContact
        {
            get
            {
                return _EmergencyContact;
            }
            set
            {
                OnEmergencyContactChanging(value);
                ReportPropertyChanging("EmergencyContact");
                _EmergencyContact = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmergencyContact");
                OnEmergencyContactChanged();
            }
        }
        private global::System.String _EmergencyContact;
        partial void OnEmergencyContactChanging(global::System.String value);
        partial void OnEmergencyContactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfRegistration
        {
            get
            {
                return _DateOfRegistration;
            }
            set
            {
                OnDateOfRegistrationChanging(value);
                ReportPropertyChanging("DateOfRegistration");
                _DateOfRegistration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfRegistration");
                OnDateOfRegistrationChanged();
            }
        }
        private global::System.DateTime _DateOfRegistration;
        partial void OnDateOfRegistrationChanging(global::System.DateTime value);
        partial void OnDateOfRegistrationChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="baxtech_clinicModel", Name="OccupiedBeds_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class OccupiedBeds_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OccupiedBeds_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="bedName">Initial value of the BedName property.</param>
        /// <param name="ratePerDay">Initial value of the RatePerDay property.</param>
        /// <param name="patientId">Initial value of the PatientId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static OccupiedBeds_Result CreateOccupiedBeds_Result(global::System.Int32 id, global::System.String bedName, global::System.Decimal ratePerDay, global::System.Int32 patientId, global::System.String name)
        {
            OccupiedBeds_Result occupiedBeds_Result = new OccupiedBeds_Result();
            occupiedBeds_Result.Id = id;
            occupiedBeds_Result.BedName = bedName;
            occupiedBeds_Result.RatePerDay = ratePerDay;
            occupiedBeds_Result.PatientId = patientId;
            occupiedBeds_Result.Name = name;
            return occupiedBeds_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BedName
        {
            get
            {
                return _BedName;
            }
            set
            {
                OnBedNameChanging(value);
                ReportPropertyChanging("BedName");
                _BedName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BedName");
                OnBedNameChanged();
            }
        }
        private global::System.String _BedName;
        partial void OnBedNameChanging(global::System.String value);
        partial void OnBedNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal RatePerDay
        {
            get
            {
                return _RatePerDay;
            }
            set
            {
                OnRatePerDayChanging(value);
                ReportPropertyChanging("RatePerDay");
                _RatePerDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RatePerDay");
                OnRatePerDayChanged();
            }
        }
        private global::System.Decimal _RatePerDay;
        partial void OnRatePerDayChanging(global::System.Decimal value);
        partial void OnRatePerDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PatientId
        {
            get
            {
                return _PatientId;
            }
            set
            {
                OnPatientIdChanging(value);
                ReportPropertyChanging("PatientId");
                _PatientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PatientId");
                OnPatientIdChanged();
            }
        }
        private global::System.Int32 _PatientId;
        partial void OnPatientIdChanging(global::System.Int32 value);
        partial void OnPatientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="baxtech_clinicModel", Name="VisitDetailsForVisit_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class VisitDetailsForVisit_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VisitDetailsForVisit_Result object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="symptoms">Initial value of the Symptoms property.</param>
        /// <param name="disease">Initial value of the Disease property.</param>
        /// <param name="treatment">Initial value of the Treatment property.</param>
        public static VisitDetailsForVisit_Result CreateVisitDetailsForVisit_Result(global::System.Int32 id, global::System.String symptoms, global::System.String disease, global::System.String treatment)
        {
            VisitDetailsForVisit_Result visitDetailsForVisit_Result = new VisitDetailsForVisit_Result();
            visitDetailsForVisit_Result.Id = id;
            visitDetailsForVisit_Result.Symptoms = symptoms;
            visitDetailsForVisit_Result.Disease = disease;
            visitDetailsForVisit_Result.Treatment = treatment;
            return visitDetailsForVisit_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Symptoms
        {
            get
            {
                return _Symptoms;
            }
            set
            {
                OnSymptomsChanging(value);
                ReportPropertyChanging("Symptoms");
                _Symptoms = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Symptoms");
                OnSymptomsChanged();
            }
        }
        private global::System.String _Symptoms;
        partial void OnSymptomsChanging(global::System.String value);
        partial void OnSymptomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Disease
        {
            get
            {
                return _Disease;
            }
            set
            {
                OnDiseaseChanging(value);
                ReportPropertyChanging("Disease");
                _Disease = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Disease");
                OnDiseaseChanged();
            }
        }
        private global::System.String _Disease;
        partial void OnDiseaseChanging(global::System.String value);
        partial void OnDiseaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Treatment
        {
            get
            {
                return _Treatment;
            }
            set
            {
                OnTreatmentChanging(value);
                ReportPropertyChanging("Treatment");
                _Treatment = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Treatment");
                OnTreatmentChanged();
            }
        }
        private global::System.String _Treatment;
        partial void OnTreatmentChanging(global::System.String value);
        partial void OnTreatmentChanged();

        #endregion
    }

    #endregion
    
}
